# Generated by Django 2.0.3 on 2018-03-08 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='db_edp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo_pedagogigo', models.TextField()),
                ('atividades', models.TextField()),
                ('metodologia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='db_edp_aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('resposta_video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('edp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_edp')),
            ],
        ),
        migrations.CreateModel(
            name='db_habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='db_recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('player_audio', models.NullBooleanField()),
                ('player_imagem', models.NullBooleanField()),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db_edp')),
            ],
        ),
        migrations.AddField(
            model_name='db_edp',
            name='habilidades',
            field=models.ManyToManyField(to='core.db_habilidades'),
        ),
        migrations.AddField(
            model_name='db_edp',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
