# Generated by Django 2.0.3 on 2018-03-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_edp_aluno',
            old_name='resposta_texto',
            new_name='resposta',
        ),
    ]
